# Generated by Django 4.2.11 on 2024-04-26 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0002_professor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.materia')),
            ],
        ),
    ]
