# Generated by Django 4.2.11 on 2024-05-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0002_professor_user'),
        ('programados', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programdo',
            new_name='Programado',
        ),
    ]
