# Generated by Django 4.2.11 on 2024-05-07 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turmas', '0002_professor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_1', models.FloatField(default=0.0)),
                ('nota_2', models.FloatField(default=0.0)),
                ('media', models.FloatField(default=0.0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.aluno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turmas.materia')),
            ],
        ),
    ]
